In [5]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
"understand the meaning of words",
'your videos are good', ]

In [7]:
sent

['the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
## define the vocabulary size
voc_size=10000

In [9]:
## one hot representation of the sentences
one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr


[[4779, 7571, 4471, 9735],
 [4779, 7638, 4471, 964],
 [6543, 9237, 1385, 46, 1831],
 [6543, 9237, 1385, 46, 1061],
 [8980, 4779, 4865, 4471, 501],
 [3909, 8134, 4244, 46]]

In [10]:
# word embedding representation
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_len=max([len(i.split()) for i in sent])
embeded_docs=pad_sequences(one_hot_repr, padding='pre', maxlen=sent_len)
embeded_docs

array([[   0, 4779, 7571, 4471, 9735],
       [   0, 4779, 7638, 4471,  964],
       [6543, 9237, 1385,   46, 1831],
       [6543, 9237, 1385,   46, 1061],
       [8980, 4779, 4865, 4471,  501],
       [   0, 3909, 8134, 4244,   46]])

In [13]:
print(embeded_docs)

[[   0 4779 7571 4471 9735]
 [   0 4779 7638 4471  964]
 [6543 9237 1385   46 1831]
 [6543 9237 1385   46 1061]
 [8980 4779 4865 4471  501]
 [   0 3909 8134 4244   46]]


In [14]:
#feature representation (vector size)
dim=10

In [15]:
# Create the embedding layer
embedding_layer=Embedding(voc_size, dim, input_length=sent_len)

In [16]:
embeded_docs[0]

array([   0, 4779, 7571, 4471, 9735])

In [ ]:
# initial weight representation before training
embedding_layer(embeded_docs)

<tf.Tensor: shape=(6, 5, 10), dtype=float32, numpy=
array([[[ 0.02458941, -0.03531537, -0.0123679 ,  0.01215469,
         -0.04297196,  0.01415933, -0.00254153,  0.04827585,
          0.03281094, -0.03202213],
        [ 0.01499093, -0.01512139, -0.01896892,  0.04067305,
          0.00999814,  0.04828875,  0.04216779,  0.04462324,
         -0.02450843,  0.03499379],
        [-0.01766416, -0.01940209,  0.00160543, -0.02381491,
         -0.02287573,  0.00714923,  0.0176692 , -0.03478333,
          0.01751882, -0.04099938],
        [-0.04717028, -0.0062348 , -0.03358044,  0.02309735,
          0.01504728,  0.04840109, -0.00984777,  0.04870654,
         -0.01937567, -0.01029941],
        [ 0.0409298 , -0.01306145, -0.00591052,  0.02219793,
         -0.00615929,  0.04496915, -0.02371041, -0.04171152,
          0.00982652,  0.03559351]],

       [[ 0.02458941, -0.03531537, -0.0123679 ,  0.01215469,
         -0.04297196,  0.01415933, -0.00254153,  0.04827585,
          0.03281094, -0.03202213]

In [18]:
embedding_layer(embeded_docs[0])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[ 0.02458941, -0.03531537, -0.0123679 ,  0.01215469, -0.04297196,
         0.01415933, -0.00254153,  0.04827585,  0.03281094, -0.03202213],
       [ 0.01499093, -0.01512139, -0.01896892,  0.04067305,  0.00999814,
         0.04828875,  0.04216779,  0.04462324, -0.02450843,  0.03499379],
       [-0.01766416, -0.01940209,  0.00160543, -0.02381491, -0.02287573,
         0.00714923,  0.0176692 , -0.03478333,  0.01751882, -0.04099938],
       [-0.04717028, -0.0062348 , -0.03358044,  0.02309735,  0.01504728,
         0.04840109, -0.00984777,  0.04870654, -0.01937567, -0.01029941],
       [ 0.0409298 , -0.01306145, -0.00591052,  0.02219793, -0.00615929,
         0.04496915, -0.02371041, -0.04171152,  0.00982652,  0.03559351]],
      dtype=float32)>

In [19]:
embeded_docs

array([[   0, 4779, 7571, 4471, 9735],
       [   0, 4779, 7638, 4471,  964],
       [6543, 9237, 1385,   46, 1831],
       [6543, 9237, 1385,   46, 1061],
       [8980, 4779, 4865, 4471,  501],
       [   0, 3909, 8134, 4244,   46]])